name: auto-mfa
channels:
  - conda-forge
dependencies:
  - python=3.11
  - numpy<2
  - ffmpeg=*=*lgpl*
  - montreal-forced-aligner
  - spacy
  - sudachipy
  - sudachidict-core
  - pip
  - pip:
      - openai-whisper
      - python-mecab-ko
      - jamo
      - spacy-pkuseg
      - dragonmapper
      - hanziconv
